version: "2"
services:
    newscoop:
        extends:
            file: docker/docker-newscoop.yml
            service: newscoop
        depends_on:
            - mysql

    mysql:
        extends:
            file: docker/docker-newscoop.yml
            service: mysql
volumes:
    newscoop:
